"""add exam sessions and student answers

Revision ID: d3a1cef9ae36
Revises: ce735b36eaf2
Create Date: 2026-05-19 20:25:42.390048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3a1cef9ae36'
down_revision: Union[str, Sequence[str], None] = 'ce735b36eaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('score_percentage', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['topic_id'], ['topics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_sessions_exam_id'), 'exam_sessions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_sessions_student_id'), 'exam_sessions', ['student_id'], unique=False)
    op.create_table('student_answers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option', sa.String(length=1), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_student_answers_session_id'), 'student_answers', ['session_id'], unique=False)
    op.drop_constraint(op.f('countries_code_key'), 'countries', type_='unique')
    op.create_index(op.f('ix_countries_code'), 'countries', ['code'], unique=True)
    op.create_unique_constraint(None, 'countries', ['name'])
    op.create_index(op.f('ix_questions_exam_id'), 'questions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_states_country_id'), 'states', ['country_id'], unique=False)
    op.create_unique_constraint(None, 'states', ['country_id', 'code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'states', type_='unique')
    op.drop_index(op.f('ix_states_country_id'), table_name='states')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_exam_id'), table_name='questions')
    op.drop_constraint(None, 'countries', type_='unique')
    op.drop_index(op.f('ix_countries_code'), table_name='countries')
    op.create_unique_constraint(op.f('countries_code_key'), 'countries', ['code'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_student_answers_session_id'), table_name='student_answers')
    op.drop_table('student_answers')
    op.drop_index(op.f('ix_exam_sessions_student_id'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_exam_id'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    # ### end Alembic commands ###
